# Generated by Django 3.2.6 on 2021-08-22 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('demo_sample', models.FileField(upload_to='audio/releases/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='band logo')),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField(help_text='Write about releases, press mention or tour dates')),
            ],
        ),
        migrations.CreateModel(
            name='BandSubmissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.label')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
