# Generated by Django 3.2.6 on 2021-08-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='public_id',
            new_name='trade_id',
        ),
    ]
