# Generated by Django 3.2.7 on 2021-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_delete_favouriterelease'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(related_name='wished_by_profiles', to='releases.Release'),
        ),
    ]
