# Generated by Django 3.2.7 on 2021-09-21 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_label_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='users.profile'),
        ),
    ]
