# Generated by Django 3.2.7 on 2021-10-03 21:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='label_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='AF', max_length=2),
            preserve_default=False,
        ),
    ]
