# Generated by Django 3.2.7 on 2021-09-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_label_is_main'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('profile',), name='unique_main_label_per_profile'),
        ),
    ]
