# Generated by Django 3.2.7 on 2021-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_wishlist'),
        ('users', '0004_auto_20211003_2104'),
    ]

    operations = [
    ]
