# Generated by Django 3.2 on 2021-06-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='label_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
