# Generated by Django 3.2.7 on 2021-09-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_label_unique_main_label_per_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-is_main']},
        ),
    ]
