# Generated by Django 3.2 on 2021-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencies', models.CharField(blank=True, choices=[('USD', 'American Dollar'), ('EUR', 'Euro'), ('UAH', 'Ukrainian Hrivna')], default='USD', max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='currencies',
        ),
        migrations.AddField(
            model_name='profile',
            name='currencies',
            field=models.ManyToManyField(to='users.Currencies'),
        ),
    ]
