# Generated by Django 3.2 on 2021-06-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210619_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currencies',
        ),
        migrations.DeleteModel(
            name='Currencies',
        ),
    ]
