# Generated by Django 3.2 on 2021-06-24 11:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210624_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AUT', 'Austria'), ('DEU', 'Germany'), ('NLD', 'Neitherlands')], max_length=11, null=True),
        ),
    ]
