# Generated by Django 3.2 on 2021-06-26 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profilecurrency_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currency',
        ),
        migrations.AddField(
            model_name='profilecurrency',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
