# Generated by Django 3.2 on 2021-06-26 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profilecurrency_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecurrency',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
