# Generated by Django 3.2 on 2021-06-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_profilecurrency_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilecurrency',
            unique_together={('currency', 'profile')},
        ),
    ]
