# Generated by Django 3.2 on 2021-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/labels/'),
        ),
    ]
