# Generated by Django 3.2 on 2021-07-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210630_1553'),
        ('users', '0031_alter_label_logo'),
    ]

    operations = [
    ]
