# Generated by Django 3.2 on 2021-07-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_0030_auto_20210630_1553_0031_alter_label_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short label description'),
        ),
        migrations.AlterField(
            model_name='label',
            name='logo',
            field=models.ImageField(blank=True, help_text='For best result - black logo on white or transparent background', null=True, upload_to='images/labels/', verbose_name='Label logo'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(help_text='Label name as you write on your releases', max_length=250, verbose_name='Label name'),
        ),
        migrations.AlterField(
            model_name='label',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_label_per_profile'),
        ),
    ]
