# Generated by Django 3.2 on 2021-07-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210707_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='users.profile'),
        ),
    ]
