# Generated by Django 3.2.5 on 2021-07-30 04:32

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_label_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='base style')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=250, verbose_name='band')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country')),
                ('album', models.CharField(max_length=250, verbose_name='album title')),
                ('date', models.DateField(verbose_name='release date')),
                ('image', models.ImageField(upload_to='images/releases/', verbose_name='image')),
                ('sample', models.FileField(upload_to='music/', verbose_name='sample music')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='users.label')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='users.style')),
            ],
        ),
    ]
