# Generated by Django 3.2.5 on 2021-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_release_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.CharField(default='ID', max_length=250, verbose_name='music_name'),
        ),
    ]
