# Generated by Django 3.2.7 on 2021-09-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public_tradelist', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to='users.profile'),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='profile_requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_requester', to='users.profile'),
        ),
    ]
