# Generated by Django 3.2.7 on 2021-09-17 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('public_tradelist', '0003_traderequest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='profile_requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_requester', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
