# Generated by Django 3.2.7 on 2021-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_tradelist', '0004_auto_20210918_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequest',
            name='profile_requester',
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
