# Generated by Django 3.2.4 on 2021-08-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleAndTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_for_trade', models.BooleanField(default=False, null=True)),
                ('trade_points', models.PositiveIntegerField(blank=True, null=True)),
                ('trade_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('available_for_wholesale', models.BooleanField(default=False, null=True)),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='releases.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseWholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_currency', to='users.profilecurrency')),
                ('wholesale_and_trades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_and_trades', to='releases.wholesaleandtrades')),
            ],
        ),
        migrations.AddConstraint(
            model_name='releasewholesaleprice',
            constraint=models.UniqueConstraint(fields=('profile_currency', 'currency_price'), name='unique_wholesaleprice_per_currency'),
        ),
    ]
