# Generated by Django 3.2.6 on 2021-08-21 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import releases.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('demo_sample', models.FileField(upload_to='audio/releases/', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/covers/', verbose_name='band logo')),
                ('biography', models.TextField(help_text='Write about releases, press mention or tour dates')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted date'),
        ),
        migrations.AlterField(
            model_name='release',
            name='base_style',
            field=models.CharField(choices=[('black_metal', 'Black Metal'), ('death_metal', 'Death Metal'), ('trash_metal', 'Thrash Metal')], max_length=250),
        ),
        migrations.AlterField(
            model_name='release',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='users.label'),
        ),
        migrations.AlterField(
            model_name='release',
            name='sample',
            field=models.FileField(help_text='Upload up to 1 minute sample of the album to give fellow label owners a taste of this release', upload_to='audios/releases/', validators=[releases.models.validate_file_size, django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
