# Generated by Django 3.2.4 on 2021-07-30 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import releases.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='users.label'),
        ),
        migrations.AlterField(
            model_name='release',
            name='sample',
            field=models.FileField(help_text='Upload up to 1 minute sample of the album to give fellow label owners a taste of this release', upload_to='audios/releases/', validators=[releases.models.validate_file_size, django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
