# Generated by Django 3.2.6 on 2021-08-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_auto_20210816_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasewholesaleprice',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_price', to='releases.release'),
        ),
    ]
