# Generated by Django 3.2.7 on 2021-10-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='base_style',
            field=models.CharField(choices=[('classical', 'Classical'), ('country', 'Country'), ('edm', 'EDM'), ('hip_hop', 'Hip-Hop'), ('indie_rock', 'Indie Rock'), ('jazz', 'Jazz'), ('k_pop', 'K-pop'), ('metal', 'Metal'), ('oldies', 'Oldies'), ('pop', 'Pop'), ('rap', 'Rap'), ('rb', 'Rhythm & blues (R&B)'), ('rock', 'Rock'), ('techno', 'Techno')], max_length=250),
        ),
    ]
