# Generated by Django 3.2.4 on 2021-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_auto_20210804_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleandtrades',
            name='available_for_trade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wholesaleandtrades',
            name='available_for_wholesale',
            field=models.BooleanField(default=False),
        ),
    ]
