# Generated by Django 3.2.6 on 2021-09-01 04:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 4, 41, 36, 366574, tzinfo=utc), verbose_name='request datetime'),
            preserve_default=False,
        ),
    ]
