# Generated by Django 3.2.7 on 2021-09-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderequestitem',
            name='release',
        ),
        migrations.RemoveField(
            model_name='traderequestitem',
            name='trade_request',
        ),
        migrations.DeleteModel(
            name='TradeRequest',
        ),
        migrations.DeleteModel(
            name='TradeRequestItem',
        ),
    ]
