# Generated by Django 3.2.7 on 2021-09-18 15:48

import configuration.file_storage
import django.core.validators
from django.db import migrations, models
import releases.models.release


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover_image',
            field=models.ImageField(help_text='Select image with minimum size of 800x800 pixel', storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='images/covers/', verbose_name='Front cover image'),
        ),
        migrations.AlterField(
            model_name='release',
            name='sample',
            field=models.FileField(help_text='Upload up to 1 minute sample of the album to give fellow label owners a taste of this release', storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='audios/releases/', validators=[releases.models.release.validate_file_size, django.core.validators.FileExtensionValidator(['mp3'])]),
        ),
    ]
