# Generated by Django 3.2.4 on 2021-08-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_auto_20210813_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
