# Generated by Django 3.2.5 on 2021-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_alter_release_base_style'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='release',
            name='base_style',
            field=models.CharField(choices=[('Black Metal', 'Black Metal'), ('Death Metal', 'Death Metal'), ('Trash Metal', 'Thrash Metal')], max_length=250),
        ),
    ]
