# Generated by Django 3.2.6 on 2021-08-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('releases', '0003_delete_test'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='releasewholesaleprice',
            name='unique_release_per_currency',
        ),
        migrations.AlterField(
            model_name='releasewholesaleprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices_for_currency', to='users.profilecurrency'),
        ),
        migrations.AlterField(
            model_name='releasewholesaleprice',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices', to='releases.release'),
        ),
        migrations.AddConstraint(
            model_name='releasewholesaleprice',
            constraint=models.UniqueConstraint(fields=('release', 'currency'), name='unique_price_per_release_and_currency'),
        ),
    ]
