# Generated by Django 3.2.4 on 2021-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_auto_20210804_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleandtrades',
            name='available_for_trade',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='wholesaleandtrades',
            name='available_for_wholesale',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='wholesaleandtrades',
            name='trade_points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
