# Generated by Django 3.2.4 on 2021-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_alter_release_base_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
