# Generated by Django 3.2.7 on 2021-09-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_alter_release_label'),
        ('releases', '0003_auto_20210918_2148'),
    ]

    operations = [
    ]
