# Generated by Django 3.2.6 on 2021-08-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_auto_20210829_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestPurchase',
        ),
    ]
