# Generated by Django 3.2.7 on 2021-09-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_alter_release_label'),
        ('releases', '0003_auto_20210918_2148'),
    ]

    operations = [
    ]
