# Generated by Django 3.2.7 on 2021-09-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('releases', '0003_auto_20210930_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriterelease',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_releases', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='favouriterelease',
            name='release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_object', to='releases.release'),
        ),
    ]
