# Generated by Django 3.2.8 on 2021-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_playlist_playlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
