# Generated by Django 3.2.5 on 2021-08-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20210731_2145'),
    ]

    operations = [

        migrations.AlterField(
            model_name='release',
            name='base_style',
            field=models.CharField(choices=[('black_metal', 'Black Metal'), ('death_metal', 'Death Metal'), ('trash_metal', 'Thrash Metal')], max_length=250),
        ),
    ]
