# Generated by Django 3.2.6 on 2021-08-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_delete_requestpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequestitem',
            name='trade_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items', to='releases.traderequest'),
        ),
    ]
