# Generated by Django 3.2.8 on 2021-10-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_alter_playlist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='release',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistItem',
        ),
    ]
