# Generated by Django 3.2.7 on 2021-10-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20210930_1923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteRelease',
        ),
    ]
