# Generated by Django 3.2.7 on 2021-09-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_merge_20210921_1931'),
        ('releases', '0004_merge_20210922_1745'),
    ]

    operations = [
    ]
