# Generated by Django 3.2.4 on 2021-08-05 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20210805_1353'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='releasewholesaleprice',
            name='unique_wholesaleprice_per_currency',
        ),
        migrations.AlterField(
            model_name='wholesaleandtrades',
            name='trade_points',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddConstraint(
            model_name='releasewholesaleprice',
            constraint=models.UniqueConstraint(fields=('wholesale_and_trades', 'profile_currency'), name='unique_wholesaleprice_per_currency'),
        ),
    ]
