# Generated by Django 3.2.4 on 2021-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_release_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release date'),
        ),
    ]
