# Generated by Django 3.2.7 on 2021-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_alter_release_base_style'),
        ('releases', '0005_delete_favouriterelease'),
    ]

    operations = [
    ]
