# Generated by Django 3.2.4 on 2021-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_auto_20210805_1453'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='releasewholesaleprice',
            name='unique_wholesaleprice_per_currency',
        ),
        migrations.AddConstraint(
            model_name='releasewholesaleprice',
            constraint=models.UniqueConstraint(fields=('wholesale_and_trades', 'profile_currency'), name='unique_wholesaleandtrades_per_currency'),
        ),
    ]
