# Generated by Django 3.2.5 on 2021-08-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_release_is_published'),
        ('releases', '0005_auto_20210801_1107'),
    ]

    operations = [
    ]
