# Generated by Django 3.2.6 on 2021-08-30 13:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_alter_traderequestitem_trade_request'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='release',
            managers=[
                ('trade_item_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
