# Generated by Django 3.2.6 on 2021-08-30 15:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_alter_release_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='release',
            managers=[
                ('trade_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
