# Generated by Django 3.2.6 on 2021-08-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_alter_release_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='release',
            managers=[
            ],
        ),
    ]
