# Generated by Django 3.2.5 on 2021-08-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0009_alter_release_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(help_text='For past/old releases exact date is not important, feel free just to select January 1st, but with correct year. For recent/upcoming releases - please try to set the date exactly. This release will be shown in Upcoming Releases section.', verbose_name='Release date'),
        ),
    ]
