# Generated by Django 3.2.7 on 2021-09-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_initial'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trade_items', to='releases.release')),
                ('trade_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trade_items', to='trades.usertraderequest')),
            ],
        ),
    ]
