version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: 
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages:
        pkg-manager: pipenv
      - run:
        command: print("My first CI is ready!")
        
workflows:
  main:
    jobs:
      - build
