version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: 
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - python/install-packages
    
        
workflows:
  main:
    jobs:
      - build
