# Generated by Django 3.2.8 on 2021-10-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('release_collections', '0002_playlist_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collection',
            new_name='ReleaseCollection',
        ),
    ]
