# Generated by Django 3.2.8 on 2021-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_collections', '0003_rename_collection_releasecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecollection',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
