from .sign_up_view_test import SignUpViewTest
from .set_as_main_label_view_test import SetAsMainLabelViewTest
from .label_detail_view_test import LabelDetailViewTest
from .delete_label_view_test import DeleteLabelViewTest
from .set_as_main_label_view_test import SetAsMainLabelViewTest
from .create_profile_currency_view_test import CreateProfileCurrencyViewTest
from .update_label_view_test import UpdateLabelViewTest
