# Generated by Django 3.2.7 on 2021-09-18 15:48

import configuration.file_storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band_submissions', '0002_bandsubmission_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandsubmission',
            name='album',
            field=models.FileField(help_text='upload zip or rar file containing your album samples', storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='band_submissions/files/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='bandsubmission',
            name='best_track',
            field=models.FileField(storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='band_submissions/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='best track'),
        ),
        migrations.AlterField(
            model_name='bandsubmission',
            name='front_cover',
            field=models.ImageField(blank=True, null=True, storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='band_submissions/image/', verbose_name='front cover'),
        ),
    ]
